{% set name = "seqeval" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6cf96d8dd2a7d1e428e5d52e28ba2b2468c77128790a0dab1cf78cb680236798

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - keras >=2.2.4
    - numpy
    - python

test:
  imports:
    - seqeval
    - seqeval.metrics

about:
  home: https://github.com/chakki-works/seqeval
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Testing framework for sequence labeling
  doc_url: https://pypi.org/project/seqeval/
  dev_url: https://github.com/chakki-works/seqeval

extra:
  recipe-maintainers:
    - oblute
    - benhuff
